modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#logoFile="examplemod.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Just Enough Items (JEI)
[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[${jei_version},)"
    ordering="AFTER"
    side="BOTH"

# The One Probe (TOP)
[[dependencies.${mod_id}]]
    modId="theoneprobe"
    type="optional"
    versionRange="[${theoneprobe_version},)"
    ordering="AFTER"
    side="BOTH"

# Jade
[[dependencies.${mod_id}]]
    modId="jare"
    type="optional"
    versionRange="[${jade_version},)"
    ordering="AFTER"
    side="BOTH"
